package View;

import Model.Cell;
import Model.Road;
import Model.RoadSense;
import Model.SemaphoreStatus;
import Model.Status;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Laura
 */
public class simulatorView extends javax.swing.JFrame {

    /**
     * Creates new form simulatorView
     */
    public simulatorView() {
        initComponents();
        initSimulatorCompontents();
        setUpSimulation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextStateButton = new javax.swing.JButton();
        simulatorPane = new javax.swing.JPanel();
        i11 = new javax.swing.JButton();
        h11 = new javax.swing.JButton();
        h12 = new javax.swing.JButton();
        v11 = new javax.swing.JButton();
        h14s = new javax.swing.JButton();
        v13 = new javax.swing.JButton();
        v12 = new javax.swing.JButton();
        v14s = new javax.swing.JButton();
        h13 = new javax.swing.JButton();
        h15p = new javax.swing.JButton();
        h16 = new javax.swing.JButton();
        h17 = new javax.swing.JButton();
        h18s = new javax.swing.JButton();
        i12 = new javax.swing.JButton();
        v24s = new javax.swing.JButton();
        v21 = new javax.swing.JButton();
        v23 = new javax.swing.JButton();
        v22 = new javax.swing.JButton();
        h19p = new javax.swing.JButton();
        h110 = new javax.swing.JButton();
        h111 = new javax.swing.JButton();
        h112o = new javax.swing.JButton();
        v15p = new javax.swing.JButton();
        v16 = new javax.swing.JButton();
        v17 = new javax.swing.JButton();
        v18s = new javax.swing.JButton();
        v25p = new javax.swing.JButton();
        v26 = new javax.swing.JButton();
        v27 = new javax.swing.JButton();
        v28s = new javax.swing.JButton();
        i22 = new javax.swing.JButton();
        h28s = new javax.swing.JButton();
        h27 = new javax.swing.JButton();
        h26 = new javax.swing.JButton();
        h25p = new javax.swing.JButton();
        i21 = new javax.swing.JButton();
        h24s = new javax.swing.JButton();
        h23 = new javax.swing.JButton();
        h22 = new javax.swing.JButton();
        h21 = new javax.swing.JButton();
        h29p = new javax.swing.JButton();
        h210 = new javax.swing.JButton();
        h211 = new javax.swing.JButton();
        h212o = new javax.swing.JButton();
        v19p = new javax.swing.JButton();
        v110 = new javax.swing.JButton();
        v111 = new javax.swing.JButton();
        v112o = new javax.swing.JButton();
        v29p = new javax.swing.JButton();
        v210 = new javax.swing.JButton();
        v211 = new javax.swing.JButton();
        v212o = new javax.swing.JButton();
        carsInTextField = new javax.swing.JTextField();
        carsInLabel = new javax.swing.JLabel();
        carsOutLabel = new javax.swing.JLabel();
        carsOutTextfield = new javax.swing.JTextField();
        proptionLabel = new javax.swing.JLabel();
        proptionTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        hSemTatusTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        iterTextField = new javax.swing.JTextField();
        resetbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nextStateButton.setText("Next");
        nextStateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextStateButtonActionPerformed(evt);
            }
        });

        simulatorPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Simulator"));

        javax.swing.GroupLayout simulatorPaneLayout = new javax.swing.GroupLayout(simulatorPane);
        simulatorPane.setLayout(simulatorPaneLayout);
        simulatorPaneLayout.setHorizontalGroup(
            simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simulatorPaneLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(simulatorPaneLayout.createSequentialGroup()
                        .addComponent(h11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(simulatorPaneLayout.createSequentialGroup()
                        .addComponent(h21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simulatorPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h14s, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(simulatorPaneLayout.createSequentialGroup()
                                .addComponent(i11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h15p, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h18s, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(v11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v14s, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v15p, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v18s, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simulatorPaneLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(h24s, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(v19p, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(simulatorPaneLayout.createSequentialGroup()
                                .addComponent(i21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(h25p, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h28s, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(v110, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v111, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v112o, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simulatorPaneLayout.createSequentialGroup()
                        .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(simulatorPaneLayout.createSequentialGroup()
                                .addComponent(i22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(h29p, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h210, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h211, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h212o, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(simulatorPaneLayout.createSequentialGroup()
                                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(v28s, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v25p, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v24s, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(simulatorPaneLayout.createSequentialGroup()
                                        .addComponent(i12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h19p, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h110, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h111, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h112o, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(v22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(simulatorPaneLayout.createSequentialGroup()
                        .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(v29p, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v210, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v211, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v212o, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        simulatorPaneLayout.setVerticalGroup(
            simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simulatorPaneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(simulatorPaneLayout.createSequentialGroup()
                        .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(simulatorPaneLayout.createSequentialGroup()
                                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simulatorPaneLayout.createSequentialGroup()
                                        .addComponent(v11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(v12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(v13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simulatorPaneLayout.createSequentialGroup()
                                        .addComponent(v21, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(v22, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(v23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(v14s, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v24s, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(h14s, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                    .addComponent(h12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(h11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(h13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(i11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(h15p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(h16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(h17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(h18s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(i12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(h19p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(h110, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(h111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(h112o, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v15p, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(v25p, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(v26, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simulatorPaneLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(v17, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v27, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(simulatorPaneLayout.createSequentialGroup()
                                .addComponent(v18s, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v19p, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(simulatorPaneLayout.createSequentialGroup()
                                .addComponent(v28s, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(i22, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v29p, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(simulatorPaneLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(h28s, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h25p, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h24s, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h212o, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h211, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h210, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(h29p, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(simulatorPaneLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(v110, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v210, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(v111, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v211, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(simulatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(v112o, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v212o, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        carsInTextField.setEditable(false);
        carsInTextField.setColumns(10);

        carsInLabel.setText("Num. Cars In:");

        carsOutLabel.setText("Num. Cars Out:");

        carsOutTextfield.setEditable(false);

        proptionLabel.setText("Proportion OUT/IN:");

        proptionTextField.setEditable(false);

        jLabel1.setText("Horizontal Sem. Status");

        hSemTatusTextField.setEditable(false);

        jLabel2.setText("Iteration");

        iterTextField.setEditable(false);

        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simulatorPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246)
                        .addComponent(nextStateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(carsInLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carsInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carsOutLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carsOutTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hSemTatusTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(proptionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(proptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(157, 157, 157)
                        .addComponent(resetbutton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simulatorPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carsInLabel)
                    .addComponent(carsInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carsOutLabel)
                    .addComponent(carsOutTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proptionLabel)
                    .addComponent(proptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hSemTatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextStateButton)
                    .addComponent(jLabel2)
                    .addComponent(iterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextStateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextStateButtonActionPerformed
        simulationUpdate();
    }//GEN-LAST:event_nextStateButtonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
       resetSimulation();
       simulationUpdate();
    }//GEN-LAST:event_resetbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simulatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simulatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simulatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simulatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simulatorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carsInLabel;
    private javax.swing.JTextField carsInTextField;
    private javax.swing.JLabel carsOutLabel;
    private javax.swing.JTextField carsOutTextfield;
    private javax.swing.JButton h11;
    private javax.swing.JButton h110;
    private javax.swing.JButton h111;
    private javax.swing.JButton h112o;
    private javax.swing.JButton h12;
    private javax.swing.JButton h13;
    private javax.swing.JButton h14s;
    private javax.swing.JButton h15p;
    private javax.swing.JButton h16;
    private javax.swing.JButton h17;
    private javax.swing.JButton h18s;
    private javax.swing.JButton h19p;
    private javax.swing.JButton h21;
    private javax.swing.JButton h210;
    private javax.swing.JButton h211;
    private javax.swing.JButton h212o;
    private javax.swing.JButton h22;
    private javax.swing.JButton h23;
    private javax.swing.JButton h24s;
    private javax.swing.JButton h25p;
    private javax.swing.JButton h26;
    private javax.swing.JButton h27;
    private javax.swing.JButton h28s;
    private javax.swing.JButton h29p;
    private javax.swing.JTextField hSemTatusTextField;
    private javax.swing.JButton i11;
    private javax.swing.JButton i12;
    private javax.swing.JButton i21;
    private javax.swing.JButton i22;
    private javax.swing.JTextField iterTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nextStateButton;
    private javax.swing.JLabel proptionLabel;
    private javax.swing.JTextField proptionTextField;
    private javax.swing.JButton resetbutton;
    private javax.swing.JPanel simulatorPane;
    private javax.swing.JButton v11;
    private javax.swing.JButton v110;
    private javax.swing.JButton v111;
    private javax.swing.JButton v112o;
    private javax.swing.JButton v12;
    private javax.swing.JButton v13;
    private javax.swing.JButton v14s;
    private javax.swing.JButton v15p;
    private javax.swing.JButton v16;
    private javax.swing.JButton v17;
    private javax.swing.JButton v18s;
    private javax.swing.JButton v19p;
    private javax.swing.JButton v21;
    private javax.swing.JButton v210;
    private javax.swing.JButton v211;
    private javax.swing.JButton v212o;
    private javax.swing.JButton v22;
    private javax.swing.JButton v23;
    private javax.swing.JButton v24s;
    private javax.swing.JButton v25p;
    private javax.swing.JButton v26;
    private javax.swing.JButton v27;
    private javax.swing.JButton v28s;
    private javax.swing.JButton v29p;
    // End of variables declaration//GEN-END:variables

    int iteration;
    Road h, h2, v, v2;
    ArrayList<JButton> h_, h2_, v_, v2_;
    boolean horizontalSemaphoreOpen;

    private void initSimulatorCompontents() {
        iteration = 0;
        h = new Road(RoadSense.Horizontal);
        h2 = new Road(RoadSense.Horizontal);
        v = new Road(RoadSense.Vertical);
        v2 = new Road(RoadSense.Vertical);

        h.intersectRoads(v, 1, 1);
        h.intersectRoads(v2, 2, 1);
        h2.intersectRoads(v, 1, 2);
        h2.intersectRoads(v2, 2, 2);

        h_ = new ArrayList<>();
        h2_ = new ArrayList<>();
        v_ = new ArrayList<>();
        v2_ = new ArrayList<>();

        h_.add(h11);
        h_.add(h12);
        h_.add(h13);
        h_.add(h14s);
        h_.add(i11);
        h_.add(h15p);
        h_.add(h16);
        h_.add(h17);
        h_.add(h18s);
        h_.add(i12);
        h_.add(h19p);
        h_.add(h110);
        h_.add(h111);
        h_.add(h112o);

        h2_.add(h21);
        h2_.add(h22);
        h2_.add(h23);
        h2_.add(h24s);
        h2_.add(i21);
        h2_.add(h25p);
        h2_.add(h26);
        h2_.add(h27);
        h2_.add(h28s);
        h2_.add(i22);
        h2_.add(h29p);
        h2_.add(h210);
        h2_.add(h211);
        h2_.add(h212o);

        v_.add(v11);
        v_.add(v12);
        v_.add(v13);
        v_.add(v14s);
        v_.add(i11);
        v_.add(v15p);
        v_.add(v16);
        v_.add(v17);
        v_.add(v18s);
        v_.add(i21);
        v_.add(v19p);
        v_.add(v110);
        v_.add(v111);
        v_.add(v112o);

        v2_.add(v21);
        v2_.add(v22);
        v2_.add(v23);
        v2_.add(v24s);
        v2_.add(i12);
        v2_.add(v25p);
        v2_.add(v26);
        v2_.add(v27);
        v2_.add(v28s);
        v2_.add(i22);
        v2_.add(v29p);
        v2_.add(v210);
        v2_.add(v211);
        v2_.add(v212o);
    }

    private void cellViewUpdate(JButton view, Cell c) {
        if (c.currentStatus == Status.FREE) {
            view.setBackground(Color.GREEN);
        } else {
            view.setBackground(Color.darkGray);
        }
    }

    private void roadViewUpdate() {
        for (int i = 0; i < 14; i++) {
            cellViewUpdate(h_.get(i), h.getCellIn(i));
            cellViewUpdate(h2_.get(i), h2.getCellIn(i));
            cellViewUpdate(v_.get(i), v.getCellIn(i));
            cellViewUpdate(v2_.get(i), v2.getCellIn(i));
        }
    }

    private void roadDataUpdate() {
        //h.determineNextStatusAndUpdate();
        //h2.determineNextStatusAndUpdate();
        //v.determineNextStatusAndUpdate();
        //v2.determineNextStatusAndUpdate();
        updateSimulator();
    }

    private void addCarsToDataRoads() {
        h.addCar();
        h2.addCar();
        v.addCar();
        v2.addCar();

    }

    private void simulationUpdate() {
        iteration += 1;
        iterTextField.setText(String.valueOf(iteration));
        addCarsToDataRoads();
        if (iteration % 10 == 0) {
            if (horizontalSemaphoreOpen) {
                hSemTatusTextField.setText("OPEN");
                determineSemaphoreStatusToOpen();
            } else {
                hSemTatusTextField.setText("CLOSED");
                determineSemaphoreToClose();
            }
            horizontalSemaphoreOpen = !horizontalSemaphoreOpen;
        }
        roadDataUpdate();
        roadViewUpdate();
        infoViewUpdate();
    }

    private void infoViewUpdate() {
        updateCarsIn();
        updateCarsOut();
        updateProportion();
    }

    private void updateCarsIn() {
        carsInTextField.setText(String.valueOf(iteration * 4));
    }

    private void updateCarsOut() {
        int out = 0;
        out += h.count();
        out += h2.count();
        out += v.count();
        out += v2.count();
        carsOutTextfield.setText(String.valueOf(out));
    }

    private void updateProportion() {
        proptionTextField.setText(
                String.valueOf(
                        Float.parseFloat(carsOutTextfield.getText())
                        / Float.parseFloat(carsInTextField.getText())
                )
        );
    }

    private void setUpSimulation() {
        determineSemaphoreStatusToOpen();
        simulationUpdate();
        hSemTatusTextField.setText("OPEN");
    }

    private void determineSemaphoreStatusToOpen() {
        h.sem1NextStatus(true);
        h.sem2NextStatus(true);
        h2.sem1NextStatus(true);
        h2.sem2NextStatus(true);
        v.sem1NextStatus(false);
        v.sem2NextStatus(false);
        v2.sem1NextStatus(false);
        v2.sem2NextStatus(false);
    }

    private void determineSemaphoreToClose() {
        h.sem1NextStatus(!true);
        h.sem2NextStatus(!true);
        h2.sem1NextStatus(!true);
        h2.sem2NextStatus(!true);
        v.sem1NextStatus(!false);
        v.sem2NextStatus(!false);
        v2.sem1NextStatus(!false);
        v2.sem2NextStatus(!false);
    }

    //RECUERDA ELIMINARME :)
    private void updateSimulator() {
        h.determineNextStatusInRange(0, 3);//a
        h.updateInRange(0, 2);
        v.determineNextStatusInRange(0, 3);//b
        v.updateInRange(0, 2);
        v2.determineNextStatusInRange(0, 3); //c
        v2.updateInRange(0, 2);
        h2.determineNextStatusInRange(0, 3); //h
        h2.updateInRange(0, 2);

        //First intersection TOP+LEFT
        if (h.sem1.semStatus == SemaphoreStatus.OPEN) {
            h.determineNextStatusInRange(4, 8); //j
            v.determineNextStatusInRange(5, 8); //i
            h.updateInRange(3, 7);
            v.updateInRange(3, 3);
            v.updateInRange(5, 7);
        } else {
            v.determineNextStatusInRange(4, 8); //i
            h.determineNextStatusInRange(5, 8); //j
            v.updateInRange(3, 7);
            h.updateInRange(3, 3);
            h.updateInRange(5, 7);
        }

        //TOP+RIGHT
        if (h.sem2.semStatus == SemaphoreStatus.OPEN) {
            h.determineNextStatusInRange(9, 13); //d
            v2.determineNextStatusInRange(5, 8); //k
            h.updateInRange(8, 13);
            v2.updateInRange(3, 3);
            v2.updateInRange(5, 7);
        } else {
            v2.determineNextStatusInRange(4, 8);//k
            h.determineNextStatusInRange(10, 13); //d
            v2.updateInRange(3, 7);
            h.updateInRange(8, 8);
            h.updateInRange(10, 13);
        }

        //BOTTOM LEFT
        if (h2.sem1.semStatus == SemaphoreStatus.OPEN) {
            h2.determineNextStatusInRange(4, 8);
            v.determineNextStatusInRange(10, 13);
            h2.updateInRange(3, 7);
            v.updateInRange(8, 8);
            v.updateInRange(10, 13);
        } else {
            v.determineNextStatusInRange(9, 13);
            h2.determineNextStatusInRange(5, 8);
            v.updateInRange(8, 13);
            h2.updateInRange(3, 3);
            h2.updateInRange(5, 7);
        }

        //BOTTOM RIGHT
        if (h2.sem2.semStatus == SemaphoreStatus.OPEN) {
            h2.determineNextStatusInRange(9, 13);
            v2.determineNextStatusInRange(10, 13);
            h2.updateInRange(8, 13);
            v2.updateInRange(8, 8);
            v2.updateInRange(10, 13);
        } else {
            v2.determineNextStatusInRange(9, 13);
            h2.determineNextStatusInRange(10, 13);
            v2.updateInRange(8, 13);
            h2.updateInRange(8, 8);
            h2.updateInRange(10, 13);
        }
    }

    private void resetSimulation() {
        v.reset();
        v2.reset();
        h.reset();
        h2.reset();
        iteration = 0;
    }
}
